### ISSUE TITLE
New settings - affected/ignored forums

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Image-auto-resizer#2]

**Comment by effone** [comment]
Is this really required?
If the goal is to save space and deliver content fast; that should be globally for entire site.

**Comment by Eldenroot** [comment]
I think it is good idea.

Imagine the situation - you have a board with dedicated forums where users can upload photos etc. in high resolution. However in other parts of board there is a common content.

So in this case I would like to ignore some forums to not resize images (photos). Moreover this could be also required if you add optimise library and you will wanna skip these photos too.
