### ISSUE TITLE
Add MyBB codename for easier updates

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Image-auto-resizer#4]

**Comment by lairdshaw** [comment]
Do you mean something more than what [line 48](https://github.com/mybbgroup/Image-auto-resizer/blob/v1.0.2/root/inc/plugins/auto_resizer.php#L48) of the main plugin file does?

**Comment by Eldenroot** [comment]
Nope, it was something what I was not to be sure... because this mod was not uploaded on mybb extend site where you get own codename so it was a note just for me to check it :)
