### ISSUE TITLE
Bug with the latest version - rotated images are broken after upload and resizing

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/Image-auto-resizer#8]
@lairdshaw 

Since I upgraded to the latest version, some of the images are broken

https://www.carcassonneforum.cz/attachment.php?aid=10590

Check this - the original image is resized but then it is not "complete", lets say the bottom part is missing (grey color) 
![image](https://user-images.githubusercontent.com/778890/145240265-f39b1085-8247-43ab-ab22-bddaaaf74b4e.png)

Thumbnails is fine, generated correctly:
![image](https://user-images.githubusercontent.com/778890/145240177-a5ec23e7-0126-46bd-923e-fa1f19751bf2.png)

Not happens to every image....

**Comment by Eldenroot** [comment]
OK, it is because of auto-resizing feature with images which were rotated before you uploaded them...

**Comment by lairdshaw** [comment]
Oh, good, I was hoping you'd come up with a more specific problem description. Have you got an image for upload on which you can reliably reproduce this problem? If so, can you please share it with me as it will be useful for debugging.

**Comment by Eldenroot** [comment]
I can send you over Discord

**Comment by lairdshaw** [comment]
Fixed in version 1.0.4, just released (see commit 03ed2a5819ef5a77afbcd8d7a3e074ae71878223).
